# Matrix 矩阵运算

In [1]:
import numpy as np

In [20]:
A = np.array ([[1,2,3],[4,5,6]])
B = np.array ([[6,5,4],[3,2,1]])
C = np.array([[1,2],[3,4],[5,6]])

## 1. Addition

In [4]:
A+B

array([[7, 7, 7],
       [7, 7, 7]])

In [8]:
A+3

array([[4, 5, 6],
       [7, 8, 9]])

## 2. Subtraction

In [5]:
A-B

array([[-5, -3, -1],
       [ 1,  3,  5]])

## 3. Multiplication

In [14]:
A*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [43]:
np.dot(A,C)

array([[22, 28],
       [49, 64]])

In [22]:
A@C

array([[22, 28],
       [49, 64]])

In [35]:
c1 = np.arange(4)
print(c1)

[0 1 2 3]


In [36]:
c2 = np.arange(4).reshape(2,2)
print (c2)

[[0 1]
 [2 3]]


In [37]:
d1 = np.arange(3,9)
print(d1)

[3 4 5 6 7 8]


In [38]:
d1 = np.arange(3,9).reshape(2,3)
print(d1)

[[3 4 5]
 [6 7 8]]


In [39]:
c,d = np.arange(4).reshape(2,2), np.arange(3,9).reshape(2,3)

In [41]:
# Multiplication
np.dot(c,d)

array([[ 6,  7,  8],
       [24, 29, 34]])

## 4. Transpose 转置

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 5. Diagonal Matrix 对角矩阵

In [13]:
# Diagonal Matrix 对角矩阵
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
D = np.diag ([2,4,3,1])
x = np.array([3,2,2,7])

In [10]:
np.dot(D,x)

array([6, 8, 6, 7])

In [13]:
D@x

array([6, 8, 6, 7])

# 6. 对称矩阵

# 7. Identity Matrix 单位矩阵

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])